[build]
# This will be your default build command
  command = "npm install --no-audit && npm run build"
# This is the directory that you are publishing from (relative to root of your repo)
  publish = "dist/"